os: linux
language: node_js
node_js: '8.0.0'
services:
  - docker
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install wine -qq
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: "./Build/Releases/*"
  on:
    repo: etaletai13/MSCPlayer
    tags: true
